/*
 * Copyright 2023 The Kubernetes Authors.
 * Modified by IBM Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package handler

import (
	"fmt"
	"os"
	"path/filepath"

	klog "k8s.io/klog/v2"

	conf "github.com/ibm-aiu/dra-driver-spyre/internal/handler/config"
	cst "github.com/ibm-aiu/dra-driver-spyre/pkg/const"
	"github.com/ibm-aiu/dra-driver-spyre/pkg/flags"
	"github.com/ibm-aiu/dra-driver-spyre/pkg/types"
	"github.com/ibm-aiu/dra-driver-spyre/pkg/utils"
	cdiapi "tags.cncf.io/container-device-interface/pkg/cdi"
	cdiparser "tags.cncf.io/container-device-interface/pkg/parser"
	cdispec "tags.cncf.io/container-device-interface/specs-go"
)

const (
	cdiVendor = "k8s." + cst.DriverName
	cdiClass  = "spyre"
	cdiKind   = cdiVendor + "/" + cdiClass

	cdiCommonDeviceName = "common"
)

var (
	vfioMount = cdispec.DeviceNode{
		Path:        "/dev/vfio/vfio",
		HostPath:    "/dev/vfio/vfio",
		Permissions: "mrw",
	}
	extChoices = []string{".yaml", ".json"}
)

type CDIHandler struct {
	cache         *cdiapi.Cache
	root          string
	configHandler *conf.ConfigHandler
}

func NewCDIHandler(config *flags.Config) (*CDIHandler, error) {
	cdiRoot := config.Flags.CDIRoot
	cache, err := cdiapi.NewCache(
		cdiapi.WithSpecDirs(cdiRoot),
	)
	if err != nil {
		return nil, fmt.Errorf("unable to create a new CDI cache: %w", err)
	}
	configHandler, err := conf.InitConfigMount()
	if err != nil {
		return nil, fmt.Errorf("unable to init a config handler: %w", err)
	}
	handler := &CDIHandler{
		cache:         cache,
		root:          cdiRoot,
		configHandler: configHandler,
	}
	if err != nil {
		klog.Warningf("unable to clean pending config folder: %v", err)
	}
	return handler, nil
}

// CreateCommonSpecFile creates a default spec file.
func (cdi *CDIHandler) CreateCommonSpecFile() error {
	spec := &cdispec.Spec{
		Kind: cdiKind,
		Devices: []cdispec.Device{
			{
				Name: cdiCommonDeviceName,
				ContainerEdits: cdispec.ContainerEdits{
					Env: []string{
						fmt.Sprintf("KUBERNETES_NODE_NAME=%s", os.Getenv("NODE_NAME")),
						fmt.Sprintf("DRA_RESOURCE_DRIVER_NAME=%s", cst.DriverName),
					},
				},
			},
		},
	}

	minVersion, err := cdiapi.MinimumRequiredVersion(spec)
	if err != nil {
		return fmt.Errorf("failed to get minimum required CDI spec version: %v", err)
	}
	spec.Version = minVersion

	specName, err := cdiapi.GenerateNameForTransientSpec(spec, cdiCommonDeviceName)
	if err != nil {
		return fmt.Errorf("failed to generate Spec name: %w", err)
	}

	return cdi.cache.WriteSpec(spec, specName)
}

// CreateClaimSpecFile generates CDI spec.
// cdi spec file is created in /var/run/cdi by default.
// This function is called at Prepare.
func (cdi *CDIHandler) CreateClaimSpecFile(claimUID string, productId types.ProductID, devices types.PreparedDevices) (*cdispec.Spec, error) { //nolint:lll
	specName := cdiapi.GenerateTransientSpecName(cdiVendor, cdiClass, claimUID)

	spec := &cdispec.Spec{
		Kind:    cdiKind,
		Devices: []cdispec.Device{},
	}

	deviceIDs := GetDeviceIDs(devices)

	configMounts, err := cdi.configHandler.GetConfigMetricsMount(productId, deviceIDs)
	if err != nil {
		return spec, fmt.Errorf("failed to get config mounts: %w", err)
	}
	commonEnvs := []string{
		GetDeviceEnvs(deviceIDs),
	}
	for i, device := range devices {
		envs := []string{}
		envs = append(envs, fmt.Sprintf("AIU_DEVICE_%d=%s", i, device.PciAddress))
		cdiDevice := cdispec.Device{
			Name: device.DeviceName,
			ContainerEdits: cdispec.ContainerEdits{
				Env:         envs,
				DeviceNodes: device.CDIDeviceSpec,
			},
		}
		spec.Devices = append(spec.Devices, cdiDevice)
	}
	klog.Infof("Common Envs: %v", commonEnvs)
	klog.Infof("Config Mounts: %v", configMounts)
	spec.ContainerEdits = cdispec.ContainerEdits{
		Mounts: configMounts,
		Env:    commonEnvs,
	}
	if !utils.IsPseudoDeviceMode() {
		spec.ContainerEdits.DeviceNodes = []*cdispec.DeviceNode{&vfioMount}
	}

	minVersion, err := cdiapi.MinimumRequiredVersion(spec)
	if err != nil {
		return spec, fmt.Errorf("failed to get minimum required CDI spec version: %v", err)
	}
	spec.Version = minVersion

	return spec, cdi.cache.WriteSpec(spec, specName)
}

// DeleteClaimSpec deletes CDI spec file generated by CreateClaimSpecFile.
// This function is called at Unprepare.
func (cdi *CDIHandler) DeleteClaimSpec(claimUID string) error {
	// clean config files from spec
	specName := cdiapi.GenerateTransientSpecName(cdiVendor, cdiClass, claimUID)
	return cdi.cache.RemoveSpec(specName)
}

// ReadSpec returns cdi spec from claimUID
func (cdi *CDIHandler) ReadSpec(claimUID string) (*cdiapi.Spec, error) {
	specName := cdiapi.GenerateTransientSpecName(cdiVendor, cdiClass, claimUID)
	specFilePath, err := cdi.getSpecFilePath(specName)
	if err != nil {
		return nil, err
	}
	return cdiapi.ReadSpec(specFilePath, 0)
}

func (cdi *CDIHandler) getSpecFilePath(specName string) (string, error) {
	path := filepath.Join(cdi.root, specName)
	var err error
	for _, ext := range extChoices {
		pathWithExt := path + ext
		_, err = os.Stat(pathWithExt)
		if !os.IsNotExist(err) {
			return pathWithExt, nil
		}
	}
	return "", err
}

// GetClaimDevices parses device IDs to qualified cdi devices (prefixed with vendor and class)
func GetClaimDevices(devices []string) []string {
	cdiDevices := []string{
		cdiparser.QualifiedName(cdiVendor, cdiClass, cdiCommonDeviceName),
	}

	for _, device := range devices {
		cdiDevice := cdiparser.QualifiedName(cdiVendor, cdiClass, device)
		cdiDevices = append(cdiDevices, cdiDevice)
	}

	return cdiDevices
}

// GetDeviceIDs returns device ids from prepared devices' information.
func GetDeviceIDs(devices types.PreparedDevices) []string {
	deviceIDs := []string{}
	for _, device := range devices {
		deviceIDs = append(deviceIDs, device.PciAddress)
	}
	return deviceIDs
}

// GetDeviceEnvs returns an environment PCIDEVICE_IBM_COM_AIU_PF = list of assigned devices.
func GetDeviceEnvs(deviceIDs []string) string {
	values := ""
	lastIndex := len(deviceIDs) - 1
	for i, s := range deviceIDs {
		values += s
		if i == lastIndex {
			break
		}
		values += ","
	}
	return fmt.Sprintf("%s=%s", cst.DeviceEnvKey, values)
}

// CleanZombieConfigFolders removes all config file path those are not referred in CDI specs.
func (cdi *CDIHandler) CleanZombieConfigFolders() error {
	existingMounts := make(map[string]bool)
	// Walk through the directory
	err := filepath.Walk(cdi.root, func(path string, info os.FileInfo, err error) error {
		// skip filepath walk error
		if err != nil {
			return err
		}

		// Check if it's a directory and not the base directory itself
		if path != cdi.root {
			spec, err := cdiapi.ReadSpec(path, 0)
			if err != nil {
				klog.Infof("failed to read spec from %s: %v", path, err)
				// skip spec read error
				return nil
			}
			for _, pluginMnt := range spec.ContainerEdits.Mounts {
				existingMounts[pluginMnt.HostPath] = true
			}
		}
		return nil
	})
	if err != nil {
		return err
	}
	configHostPath := utils.GetConfigHostPath()
	metricsHostPath := utils.GetMetricsHostPath()
	klog.Infof("existing mount path: %v", existingMounts)
	generatedConfigEntries, err := os.ReadDir(configHostPath)
	klog.Infof("host configs: %v", generatedConfigEntries)
	if err != nil {
		return err
	}
	for _, entry := range generatedConfigEntries {
		fullPath := filepath.Join(configHostPath, entry.Name())
		metricsPath := filepath.Join(metricsHostPath, entry.Name())
		if _, found := existingMounts[fullPath]; !found {
			deleteMountedPath(fullPath)
			deleteMountedPath(metricsPath)
		}
	}
	return err
}

// DeleteConfigFile removes generated senlig config file.
// This function is called at Unprepare.
func (cdi *CDIHandler) DeleteConfigFile(spec *cdiapi.Spec) {
	mnts := spec.ContainerEdits.Mounts
	for _, mnt := range mnts {
		if IsHostMountedFile(mnt.ContainerPath) {
			deleteMountedPath(mnt.HostPath)
		}
	}
}

// IsHostMountedFile checks if the current mounted path match the config/metrics path.
func IsHostMountedFile(containerPath string) bool {
	return containerPath == utils.GetConfigContainerPath() || containerPath == utils.GetMetricsContainerPath()
}

func deleteMountedPath(path string) {
	if err := os.RemoveAll(path); err != nil {
		klog.Errorf("failed to clean %s", path)
	} else {
		klog.Infof("clean unmounted %s", path)
	}
}
